Added HUD
mathiasgredal/1-Semesterprojekt-Civil-Gruppe-5.2 pull request #39
Opened 2021-12-07 16:28 UTC by Storeogfede0209

2021-12-07 22:32 UTC, Nolle10 commented
Just a quick reminder for tomorrow, we should add a DecimalFormatter to the doubles, since they can get quite large.

2021-12-08 10:12 UTC, mathiasgredal requested changes
Almost good, you just need to fix some of the string formatting issues

2021-12-08 10:12 UTC, mathiasgredal commented on src/main/java/worldofzuul/presentation/SceneController.java
> +            yearLabel.setText(String.format("Year: " + (2010 + Game.instance.getGameYear())));
Why are you using string concatenation inside string.format?

2021-12-08 10:41 UTC, mathiasgredal approved these changes
LGTM(Lets get this merged)

2021-12-08 10:41 UTC, merged