View house
mathiasgredal/1-Semesterprojekt-Civil-Gruppe-5.2 pull request #48
Opened 2021-12-08 15:46 UTC by frmad

2021-12-08 15:48 UTC, Nolle10 approved these changes
LGTM

2021-12-08 15:54 UTC, mathiasgredal requested changes
Can you add a new year button to the main scene

2021-12-08 17:04 UTC, Nolle10 commented
> Can you add a new year button to the main scene

There is no need, since we have one inside of the house

2021-12-09 09:15 UTC, mathiasgredal approved these changes
LGTM

2021-12-09 09:15 UTC, mathiasgredal commented on src/main/java/worldofzuul/presentation/ViewHouseController.java
> +
Why these blank lines?

2021-12-09 09:15 UTC, mathiasgredal commented on src/main/java/worldofzuul/presentation/ViewHouseController.java
> +
Why the blank line?

2021-12-09 09:15 UTC, merged